use subshell to test existenceo phwd

diff --git a/bash_money_utilz b/bash_money_utilz
--- a/bash_money_utilz
+++ b/bash_money_utilz
@@ -41,7 +41,7 @@ function style::tab()
 	style::tab8 $1
 }
 
-if ! [[ -d ${phwd} ]]
+if ! ( cd ${phwd} )
 then
-	echo "Error: you haven't defined env 'phwd' yet. Some eggy shortcuts will fail."
+	echo "Warning: some eggy shortcuts will fail."
 fi
